# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca91848e0d10bea5229e061d05bd17489964153c0e06c87e72eceabd46aa87c276ba03fbc8834f9d2b6407938f01212bf43b0e5d6271d600a92cfa817d7110d

test:
  secret_key_base: e97b8741072625d94f13ba2eb489493acc3bd6e1a9ae9680f913b36acb5922a9cd38f102a6df47891d8433f4837606d0dd2b4f443b4c08e1bd136c6a33ab13c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
